# 1. Load the dataset
# 2. Basic preprocessing
# 3. Training Processing
   # Create the model
   # Forward Pass
   # Loss calculation
   # Back propagation
   # Parameters update
# 4. model evaluation

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv')

In [ ]:
df.head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,NaN
8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720,NaN
9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id' , 'Unnamed: 32'] , inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# train test split

In [ ]:
X_train , x_test , y_train , y_test = train_test_split(df.iloc[:,1:] , df.iloc[:,0] , test_size=0.2)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
x_test = scaler.transform(x_test)

### fit(): The scaler calculates the mean and standard deviation of each feature specifically in your training set.transform(): It applies the math formula to actually scale the numbers.The formula for standardization (Z-score) is: \(z = \frac{x - \mu}{\sigma}\)(Where x is your data point, μ is the mean, and σ is the standard deviation).

## . It Prevents Data LeakageIf you use fit_transform() on x_test, the scaler calculates a new mean and standard deviation based on the test set. This is a severe machine learning error called data leakage. Your model inadvertently gains information about the distribution of the test set, leading to overly optimistic and unrealistic performance metrics.

## fit: Computes and stores (mean) and(standard deviation) from X_train.
## transform(X_train): Uses those stored values to scale
## X_train.transform(x_test): Uses those same stored values to scale x_test

### The Training Phase (Building the Scale)Before the exam, you give your students a practice worksheet to study.You look at the worksheet and find that the average score is 50%.You decide to grade on a curve based only on this worksheet.To you, a 50% is now the baseline "Average" (Zero).This is exactly what scaler.fit_transform(X_train) does. It looks at the training data, finds the average, and sets the baseline.Step 2: The Testing Phase (The Blind Exam)Now, it is final exam day. You hand out a brand new Test (x_test).Your students need to take this test to prove they actually understand math, not just memorized the practice sheet.If you use fit_transform() on the test data, it means you change the grading curve based on how they did on the final exam.What if the final exam was incredibly easy, and the new average score is 90%?If you recalculate the curve based on the test, a student who got a 90% is now labeled as just "Average" (Zero).But your machine learning model was trained to think that "Average" means a 50% knowledge level!By changing the curve, a 90% on the test gets treated exactly the same as a 50% on the practice sheet. The numbers lose their actual meaning.The Core ProblemTo grade the final exam fairly, you must use the exact same grading curve (the mean and standard deviation) that you built from the practice worksheet.If you create a brand new curve for the final exam:You are changing the rules of the game halfway through.A score of 80 on the practice sheet and 80 on the final exam will mean completely different things to the model.

In [ ]:
X_train

array([[ 0.54558124, -0.90193439,  0.57409323, ...,  1.32140919,
         0.21510329,  0.43145609],
       [-0.96833628, -1.02780143, -0.98584533, ..., -1.25603986,
        -0.98712395, -0.9505801 ],
       [-1.84543357,  1.41262055, -1.81360176, ..., -1.00657889,
        -0.16780357,  1.33286058],
       ...,
       [ 0.57425392, -0.34951795,  0.62395807, ...,  1.13749656,
         2.30687837,  2.31290323],
       [-0.48090072, -0.692156  , -0.37957193, ...,  0.31696329,
         0.56958476,  1.14506798],
       [ 1.52331964, -0.13041608,  1.50074826, ...,  1.44558951,
         0.62810765,  0.36396812]])

In [ ]:
y_train

330    M
144    B
539    B
568    B
432    M
      ..
7      M
194    M
34     M
485    B
487    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### fit(): Creates the dictionary / rulebook by looking at your categories. For example: {'Cat': 0, 'Dog': 1, 'Fish': 2}.transform(): Uses that rulebook to actually convert the text strings into numbers.

### If you use fit_transform() on y_test, the encoder throws away the old rulebook and builds a brand new dictionary based purely on the test data alphabet.Imagine this scenario:StepDataWhat fit_transform doesResulting RulebookTraining['Cat', 'Dog']fit learns the categories. transform encodes them.Cat = 0, Dog = 1Testing['Dog', 'Cat']fit learns a new order (alphabetical or order of appearance).

### By using encoder.transform(y_test), you force the encoder to use the original training rulebook (Cat = 0, Dog = 1).Even if the test data comes in a different order like ['Dog', 'Cat'], the encoder looks at its training rulebook and outputs [1, 0]. Now, the numbers mean the exact same thing across both datasets, and your model can evaluate them correctly.

In [ ]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1])

## now conver the numpy arrays to tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
X_train_tensor

tensor([[ 0.5456, -0.9019,  0.5741,  ...,  1.3214,  0.2151,  0.4315],
        [-0.9683, -1.0278, -0.9858,  ..., -1.2560, -0.9871, -0.9506],
        [-1.8454,  1.4126, -1.8136,  ..., -1.0066, -0.1678,  1.3329],
        ...,
        [ 0.5743, -0.3495,  0.6240,  ...,  1.1375,  2.3069,  2.3129],
        [-0.4809, -0.6922, -0.3796,  ...,  0.3170,  0.5696,  1.1451],
        [ 1.5233, -0.1304,  1.5007,  ...,  1.4456,  0.6281,  0.3640]],
       dtype=torch.float64)

## NumPy arrays are hardcoded to run only on your computer's CPU.
## PyTorch tensors can be easily shifted to a GPU (Graphics Card) using a command like .to('cuda').
##  Automatic Differentiation (autograd)

In [ ]:
y_train_tensor.shape

torch.Size([455])

## Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
class NeuralNetwork():
  def __init__(self , X):
    self.weights = torch.rand(X.shape[1] , 1 ,dtype=torch.float64, requires_grad=True) # 30 rows 1 column
    self.bias = torch.zeros(1 , dtype=torch.float64 , requires_grad=True)

  def forward_pass(self , X):

    z = torch.matmul(X , self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def find_loss(self, y, y_pred):
    # clamp
      epsilon = 1e-7
      y_pred = torch.clamp(y_pred , epsilon , 1 - epsilon )  # clamp(input , min , max)
      loss = -(y_train_tensor * torch.log(y_pred) + 1 - y_train_tensor * torch.log(1 - y_pred)).mean()

      return loss

## pipeline

In [ ]:
model = NeuralNetwork(X_train_tensor)
model.weights

tensor([[0.2584],
        [0.7818],
        [0.5556],
        [0.3228],
        [0.4257],
        [0.1985],
        [0.9135],
        [0.2216],
        [0.7976],
        [0.1084],
        [0.8428],
        [0.0164],
        [0.0075],
        [0.5975],
        [0.4306],
        [0.3649],
        [0.7685],
        [0.3364],
        [0.8306],
        [0.2198],
        [0.6129],
        [0.3760],
        [0.9303],
        [0.9837],
        [0.4893],
        [0.1285],
        [0.2992],
        [0.2178],
        [0.2973],
        [0.5756]], dtype=torch.float64, requires_grad=True)

In [ ]:
# loop
for epoch in range(epochs):
# forward pass w.x + b
  y_pred = model.forward_pass(X_train_tensor)


# calc loss
  loss = model.find_loss(y_train_tensor , y_pred)


# backward pass
  loss.backward()

# parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

    # zero grads

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch : {epoch + 1} and loss : {loss.item()} ")

Epoch : 1 and loss : -1.6365274269914196
Epoch : 2 and loss : -1.6499182117493258
Epoch : 3 and loss : -1.6633089965078192
Epoch : 4 and loss : -1.6766997812653648
Epoch : 5 and loss : -1.6900905660194792
Epoch : 6 and loss : -1.7034813507774673
Epoch : 7 and loss : -1.716872135535245
Epoch : 8 and loss : -1.7302629202925075
Epoch : 9 and loss : -1.7436537050498377
Epoch : 10 and loss : -1.757044489807297
Epoch : 11 and loss : -1.7704352745656566
Epoch : 12 and loss : -1.7838260593217052
Epoch : 13 and loss : -1.7972168440777863
Epoch : 14 and loss : -1.8106076288380408
Epoch : 15 and loss : -1.8239984135922962
Epoch : 16 and loss : -1.8373891983505564
Epoch : 17 and loss : -1.850779983108647
Epoch : 18 and loss : -1.8641707678664607
Epoch : 19 and loss : -1.8775615526225973
Epoch : 20 and loss : -1.8909523373809753
Epoch : 21 and loss : -1.904343122138009
Epoch : 22 and loss : -1.9177339068959507
Epoch : 23 and loss : -1.9311246916517308
Epoch : 24 and loss : -1.9445154764094932
Epoch : 25 and loss : -1.9579062611676685

# Model evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward_pass(x_test_tensor)

  y_pred = (y_pred > 0.9).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy : {accuracy.item()}")

NameError: name 'torch' is not defined